services:
  - type: web
    name: happy-church-ruiru
    env: docker
    plan: free
    branch: main
    healthCheckPath: /health.php
    envVars:
      - key: DB_HOST
        value: "mysql://uvyjfieb0nz3gjns:ghlaCM5lBu9AdIqiljwv@blwa0wvl7pnkpndupnsv-mysql.services.clever-cloud.com:3306/blwa0wvl7pnkpndupnsv"
      - key: MYSQL_ADDON_URI
        value: "mysql://uvyjfieb0nz3gjns:ghlaCM5lBu9AdIqiljwv@blwa0wvl7pnkpndupnsv-mysql.services.clever-cloud.com:3306/blwa0wvl7pnkpndupnsv"
      - key: DB_NAME
        value: "blwa0wvl7pnkpndupnsv"
      - key: DB_USER
        value: "uvyjfieb0nz3gjns"
      - key: DB_PASS
        value: "ghlaCM5lBu9AdIqiljwv"
      - key: MAIL_FROM_NAME
        value: "HAPPY CHURCH"
      - key: GMAIL_USERNAME
        value: "simonnjoro965@gmail.com"
      - key: GMAIL_PASSWORD
        value: "idjg ffty wrcl idmn"
      - key: MAIL_HOST
        value: "smtp-relay.brevo.com"
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USERNAME
        value: "simonnjoro965@gmail.com"
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_REPLY_TO
        value: "simonnjoro965@gmail.com"
