services:
  - type: web
    name: happy-church-ruiru
    env: docker
    plan: free
    branch: main
    healthCheckPath: /health.php
    envVars:
      - key: DB_HOST
        value: "mysql://uvyjfieb0nz3gjns:ghlaCM5lBu9AdIqiljwv@blwa0wvl7pnkpndupnsv-mysql.services.clever-cloud.com:3306/blwa0wvl7pnkpndupnsv"
      - key: MYSQL_ADDON_URI
        value: "mysql://uvyjfieb0nz3gjns:ghlaCM5lBu9AdIqiljwv@blwa0wvl7pnkpndupnsv-mysql.services.clever-cloud.com:3306/blwa0wvl7pnkpndupnsv"
      - key: DB_NAME
        value: "blwa0wvl7pnkpndupnsv"
      - key: DB_USER
        value: "uvyjfieb0nz3gjns"
      - key: DB_PASS
        value: "ghlaCM5lBu9AdIqiljwv"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_NAME
        value: "Happy Church Ruiru"
